import Header from "@/components/Header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google";
import { Poppins } from "next/font/google";

export const inter = Inter({ subsets: ["latin"] });
export const monterrat = Montserrat({ subsets: ["latin"] });
export const popins = Poppins({ subsets: ["latin"],weight:['100','200','300','400','500','600','700','800','900']} );

 const metadata = {
  title: "BLACKALGO ",
  description: "Generated by create Ha_3er007",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={` ${monterrat.className} `}><Header/>{children}</body>
    </html>
  );
}
